### PR TITLE
[CDA-179] - When joining two queries in which one of them yields no r…

### PR DESCRIPTION
**Pull request by eliofreitas**
…esults an error is thrown in the CDA previewer

- Added a method in case of a join with a void table

### CODE REVIEW

**Comment by eliofreitas** [comment]
@pamval please review

**Comment by pamval** [comment]
@eliofreitas this needs an unit test

**Comment by eliofreitas** [comment]
@pamval commit updated with unit test

**Comment by pamval** [comment]
@tgf please review

**Comment by tgf** [comment]
@eliofreitas 

Please review checkstyle. https://github.com/pentaho/pentaho-coding-standards

We should favour programatic tests over file-based whenever possible, and a sql query in order to get an empty table is overkill.
These test cases seem amenable to programatic testing. Please check DataAccessTest for how to mock/extend for testing without cda files or db queries.

**Comment by eliofreitas** [comment]
@tgf updated

**Pull request merged**
