### PR TITLE
[PPP-3463] - Reflected Cross-Site (XSS) Scripting

### PR DESCRIPTION
**Pull request by akhayrutdinov**
- encode input parameter to avoid injections

@pamval, review it please or re-tag someone appropriate (`cda` is not mentioned in our cheat list). Also, if you know better fix, please do not hesitate to point it out :smile:

### CODE REVIEW

**Comment by pamval** [comment]
@tgf please review

**Comment by tgf** [comment]
@akhayrutdinov this seems to break previewer with double-encoded calls

**Comment by akhayrutdinov** [comment]
@tgf, can you please explain your remark? I thought about backwart copatibility, and from my current perspective the proposal is not breaking anything unless someone passes a `path` not being fully url-encoded

**Comment by tgf** [comment]
@akhayrutdinov my test was deploying cda in a biserver and double-clicking one of the cda samples.
had a failure in a call to listQueries from within the previewer.
the encoded path in the page was getting encoded again in the request, and reaching the resource loader encoded.
Can you confirm this?

**Comment by akhayrutdinov** [comment]
@tgf, I've updated the PR. Mind reviewing it?

**Comment by akhayrutdinov** [comment]
@tgf, review it please

**Pull request merged**
