### PR TITLE
[CDE-849] Export of table with paginate server side set as true is only exporting 10 results in a kettle data source

### PR DESCRIPTION
**Pull request by Advent51**
fixed

### CODE REVIEW

**Comment by pamval** [comment]
@jvelasques please review. I'm not entirely sure this method is only called when exporting. If this is used in dashboard query execution, then this is not the right fix.

**Comment by jvelasques** [comment]
I haven't found a use of unwrapQuery not in an export situation.
That being said, its a public endpoint, and custom use cases may exist.
Can we provide support for both cases, full export and single page support, and default it to full export?
These commits do that:
https://github.com/jvelasques/cde/commit/5a6ccf18f6872811d6787da43853c194f93b3071
https://github.com/jvelasques/cdf/commit/0ca3eaefd689dc482ba044b6906617e616e26167
They should however be improved with:
- unit tests
- a sample demonstrating the new behaviour
- an exposed property for the exportButton component in the editor
- @afrjorge's blessing ?

What do you think @pamval ?

**Comment by pamval** [comment]
I think that's a good approach. @Advent51 take a look at João's proposal, please.

**Comment by Advent51** [comment]
Ok, guys, I'll try it. Thanks.

**Pull request closed without merging**
