### PR TITLE
[CDA-160] Returning null when CalculatedColumns fails to evaluate formula

### PR DESCRIPTION
**Pull request by davidmsantos90**
@pamval @tgf please review

### CODE REVIEW

**Comment by pamval** [comment]
This is a lower level fix then I expected. What was the behavior of a calculated column in other data sources ? Has that changed ?

**Comment by davidmsantos90** [comment]
No behaviour changed. I tested it in version 15.06.30 of C-tools and this error occurred in the same conditions and also with others data sources.

This can be easily reproduced by changing this line:
https://github.com/webdetails/cda/blob/master/pentaho/src/main/resources/solution/bi-developers/cda/cdafiles/mondrian-jndi.cda#L44
To: <Formula>=[price]/0</Formula>
And running the cda file the same error will occur.

**Comment by pamval** [comment]
this does not match the jira description. The jira is specifically about the json scripting datasource and mentions that other datasources behave correctly in the same situations.

Please get together with Eduardo and figure this out.

**Comment by pamval** [comment]
@tgf, your opinion here. Should we start to consider errors in calculated columns as null values ?

**Comment by tgf** [comment]
@pamval @davidmsantos90 at first glance have no problem with it but would check with services

**Comment by tgf** [comment]
@davidmsantos90 also would like to start moving away from filetests when possible; if this only relates to postProcess we should have a test for it in TableModelUtilsTest which doesn't require reporting/kettle init

**Comment by pamval** [comment]
Services want flying pink unicorns to do their work for them. Since we surprisingly can't deliver that, they're ok with the change. 

@davidmsantos90, please do as @tgf suggests. Unit test the behavior instead of relying on a full integration test.

**Comment by davidmsantos90** [comment]
@pamval @tgf test moved to a unit test. please review

**Comment by pamval** [comment]
@tgf, review and merge if appropriate

**Comment by davidmsantos90** [comment]
@tgf you were right, I inserted the extra column in the test table by mistake, now the values being tested are the ones from the calculated column.

**Pull request merged**
