### PR TITLE
Cda maven conversion

### PR DESCRIPTION
**Pull request by diogofscmariano**

### CODE REVIEW

**Comment by pamval** [comment]
we should probably remove the cda-* folders since that's likely to cause confusion with the new core and pentaho folders

**Comment by pamval** [comment]
@tgf, please review and merge if appropriate.

**Comment by tgf** [comment]
@diogofscmariano still unable to run integration tests from maven; anything missing?

**Comment by diogofscmariano** [comment]
Option -DrunITs

**Pull request merged**
