### PR TITLE
[CDA-215] Users without 'Create Content' permission is able to edit CDA files

### PR DESCRIPTION
**Pull request by Advent51**
- permission check was added
- internationalization support was added

### CODE REVIEW

**Comment by Advent51** [comment]
@pamval please review

**Comment by pamval** [comment]
@Advent51 wingman is seriously angry at this pr, please review

**Comment by Advent51** [comment]
@pamval I checked that twice - the Wingman became crazy. For example it complains about the standard license in the file header.
Local style check passed successfully on every class.
And the test coverage cannot be affected so much by these changes as you can see.

**Comment by Advent51** [comment]
@pamval sorry, it was my fault - forget to commit and push modified CdaTestEnvironment.java

**Pull request merged**
