### PR TITLE
[PPP-3455] - Dynamic code injection vulnerabilities found

### PR DESCRIPTION
**Pull request by akhayrutdinov**
- upgrade jquery.dataTables from 1.7 to 1.10.1

According to Pedro V:
>Should be fairly straightforward. Data tables is used in CDA only to show the result of the cda query (no customizations, no advanced usage, just showing the data). 
>
>CDF is using Datatables 1.10 so I’d probably go with that (saves time on the new component process and makes it uniform).

@pamval, @diogofscmariano, @dcleao, can someone please help with these changes?

I copied files from CDF project. The minified version was taken from https://cdn.datatables.net/1.10.1/js/jquery.dataTables.min.js

In `previewer.html` there is a link to `dataTables/css/demo_table_jui.css`. It is absent among CDF's files. Also, it has some classes referring to JPG images, which are absent too. Should I remove the file with those images?

### CODE REVIEW

**Comment by pamval** [comment]
@davidmsantos90, help out here. Upgrading data tables in CDA.

**Comment by akhayrutdinov** [comment]
@davidmsantos90, did you have a chance to look at this PR?

**Comment by akhayrutdinov** [comment]
@davidmsantos90, can you please give me a hand?

**Comment by davidmsantos90** [comment]
@akhayrutdinov hey, sorry I took so long to respond.

So first I had a problem building the project with your PR. This two files are causing my build to fail (favicon.ico & Sorting icons.psd). Is this happening to you as well?

As for 'dataTables/css/demo_table_jui.css', from the search I did, this file was used in DataTables version 1.7 and being used in newer versions, also it doesn't seem we are using its rules in CDA, so I think we can remove this one.

Also needed to update previwer.html to include the new css files, also remove 'dataTables/css/demo_table_jui.css' from about.html, and the rest seems to work as it did before.

**Comment by pamval** [comment]
#190 is the full solution for this change.

**Pull request closed without merging**
